/**
 * Per-round cards — the *Per Round Cards* tab, prototype subset (spec §7).
 *
 * Each card is data: `effectId` names an implementation in engine/cards/,
 * `params` tunes it, `cueId` names its sound cue. A card that reuses an
 * existing effect (e.g. a strain-free Before & After) is a data-only change.
 * Prices follow the Shops tab defaults by rarity (3 / 5 / 8 / 12).
 */

import type { CardSpec } from '../engine/types';

export const cards: CardSpec[] = [
  // --- Extension ------------------------------------------------------------
  {
    id: 'before_and_after',
    name: 'Before & After',
    type: 'extension',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'before_and_after',
    params: { strain: 1 },
    cueId: 'wheel_sting',
    text: 'Use the tail morpheme as the start of a new dictionary word; the new letters become a new morpheme. Causes strain.',
  },
  {
    id: 'reduplication',
    name: 'Reduplication',
    type: 'extension',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'reduplication',
    params: { strain: 1 },
    cueId: 'double_clap',
    text: 'Repeat the tail morpheme as a new morpheme (bye → bye-bye). Causes strain.',
  },
  {
    id: 'hyphen',
    name: 'Hyphen',
    type: 'extension',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'hyphen',
    params: { strain: 2 },
    cueId: 'typewriter_dash',
    text: 'Append any dictionary word as a new morpheme with no overlap required. Causes double strain.',
  },
  {
    id: 'blend',
    name: 'Blend',
    type: 'extension',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'blend',
    params: { strain: 1, minOverlap: 2 },
    cueId: 'two_tones_slide',
    text: 'The new word overlaps the tail letters (not a whole morpheme): lymphatic + ticket → lymphaticket. Causes strain.',
  },
  {
    id: 'echo',
    name: 'Echo',
    type: 'extension',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'echo',
    params: {},
    cueId: 'reverb_echo',
    text: 'Copy another held card (becomes a second copy of that card).',
  },
  {
    id: 'free_morpheme',
    name: 'Free Morpheme',
    type: 'extension',
    rarity: 'exotic',
    duration: 'round',
    price: 8,
    effectId: 'free_morpheme',
    params: { strain: 1 },
    cueId: 'freedom_chord',
    text: 'Add any letters as a new morpheme with no dictionary check. Causes strain.',
  },

  // --- Sound Shift ------------------------------------------------------------
  {
    id: 'vowel_shift',
    name: 'Vowel Shift',
    type: 'sound_shift',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'vowel_shift',
    params: {},
    cueId: 'pitch_bend_up',
    text: 'Change a chosen vowel in the word to a random other vowel.',
  },
  {
    id: 'glide',
    name: 'Glide',
    type: 'sound_shift',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'glide',
    params: {},
    cueId: 'slide_whistle',
    text: 'Change a chosen vowel to Y.',
  },
  {
    id: 'elision',
    name: 'Elision',
    type: 'sound_shift',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'elision',
    params: {},
    cueId: 'pop',
    text: 'Delete one letter from the word.',
  },
  {
    id: 'metathesis',
    name: 'Metathesis',
    type: 'sound_shift',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'metathesis',
    params: {},
    cueId: 'two_tone_swap',
    text: 'Swap a chosen letter with the one after it.',
  },

  // --- Loanword ---------------------------------------------------------------
  {
    id: 'loanword',
    name: 'Loanword',
    type: 'loanword',
    rarity: 'basic',
    duration: 'run',
    price: 3,
    effectId: 'loanword',
    params: {},
    cueId: 'foreign_hello',
    text: 'Add 1 tile of a chosen letter to the pool.',
  },
  {
    id: 'simplification',
    name: 'Simplification',
    type: 'loanword',
    rarity: 'basic',
    duration: 'run',
    price: 3,
    effectId: 'simplification',
    params: { count: 3, maxValue: 1 },
    cueId: 'sweeping_broom',
    text: 'Remove 3 random tiles of base value 1 from the pool.',
  },
  {
    id: 'redraw',
    name: 'Redraw',
    type: 'loanword',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'redraw',
    params: {},
    cueId: 'card_shuffle',
    text: 'Redraw the hand (before playing any step this round).',
  },

  // --- Utility ----------------------------------------------------------------
  {
    id: 'lexicographer',
    name: 'Lexicographer',
    type: 'utility',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'lexicographer',
    params: {},
    cueId: 'page_turn',
    text: "Reveal the next Boss Round's modifier and the next round's threshold.",
  },
  {
    id: 'bank',
    name: 'Bank',
    type: 'utility',
    rarity: 'basic',
    duration: 'round',
    price: 3,
    effectId: 'bank',
    params: {},
    cueId: 'coin_cascade',
    text: 'Currency earned this round is doubled.',
  },
  {
    id: 'amendment',
    name: 'Amendment',
    type: 'utility',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'amendment',
    params: {},
    cueId: 'gavel',
    text: "Reroll the current Boss Round's negative modifier.",
  },
  {
    id: 'insurance',
    name: 'Insurance',
    type: 'utility',
    rarity: 'uncommon',
    duration: 'round',
    price: 5,
    effectId: 'insurance',
    params: {},
    cueId: 'safety_click',
    text: 'If the threshold is failed this round, no life is lost (but no shop).',
  },
];

export const cardById: ReadonlyMap<string, CardSpec> = new Map(cards.map((c) => [c.id, c]));
